---
- name: Comandos Kubernetes para desplegar
  hosts: "*"
  become: yes
  tasks:
    - name: Creamos el namespace
      community.kubernetes.k8s:
        name: webapp-volumes
        api_version: v1
        kind: Namespace
        state: present
    - name: NFS lee definicion en yaml
      community.kubernetes.k8s:
        state: present
        src: ./nfs-pv.yaml
    - name: Asignamos volumen
      community.kubernetes.k8s:
        state: present
        src: ./nfs-pvc.yaml
    - name: Desplegamos
      community.kubernetes.k8s:
        state: present
        src: ./deployment.yaml