---
# configuracion necesaria kubernetes en workers
- name: Firewall. Abrir puertos
  ansible.posix.firewalld:
    port: [10250/tcp,30000-32767/tcp]
    permanent: yes
    state: enabled
- name: Firewall reload
  systemd:
    name: firewalld
    state: reloaded
- name: Generate join token
  command: kubeadm token create --print-join-command
  register: kubeadm_join_cmd
  delegate_to: "{{ groups['masters'][0] }}"
- name: Copiamos variable con token
  set_fact:
    kubeadm_join: "{{ kubeadm_join_cmd.stdout }}"
- debug: var=kubeadm_join
- name: Store join command
  action: copy content="{{ kubeadm_join }}" dest="/etc/kubernetes/kubeadm-join.command"
- name: Run kubeadm join
  shell:  "{{ kubeadm_join }} --ignore-preflight-errors=swap"